### ISSUE TITLE
Error: Unknown column seasonal_strength in cal_features()

### ISSUE THREAD

**Issue by chintan-sd** [thiyangt/seer#1]
When using cal_features() it throws error
```
Error: Unknown column `seasonal_strength` 
In addition: Warning message:
'glue::collapse' is deprecated.
Use 'glue_collapse' instead.
See help("Deprecated") and help("glue-deprecated"). 
```
My observation is that this error occurs for quarterly time series.
Here is the code to reproduce the issue:

```
library(seer)
library(tsfeatures)
library(fpp2)

cal_features(ausbeer, database = "other", h=2, highfreq = FALSE)
```
Issue doesn't seem to occur, if seasonal = TRUE argument is supplied

Not sure, if the condition on row 118 also needs to check for seasonal argument..

Thanks

**Comment by thiyangt** [comment]
For seasonal(any series other than yearly series) time series you have to pass the argument seasonal=TRUE. So the code is;

```
library(seer)
library(tsfeatures)
library(fpp2)

cal_features(ausbeer, database = "other", h=2, highfreq = FALSE, seasonal=TRUE, m=4)
```
Condition on row 118 is not to check the seasonality. I use `tsfeatures` package to calculate stl decomposition-based features. The condition in 118 to rename the feature name "seasonal_strength" to "seasonality".  tsfeatures package uses the name seasonal_strength.  Condition on line 71 in https://github.com/thiyangt/seer/blob/master/R/feature_cal.R checks the "seasonal" condition. 

Passing the argument "m" is important if the length of the time series is less than two periods. For example, if you have a quarterly time series of length 6 (lengh(6) < 2* frequency).

**Comment by chintan-sd** [comment]
However, with the argument` seasonal = TRUE` it seems that minimum observation required in time series should be greater than (m + h), otherwise it throws error:
`Error in ts(x) : 'ts' object must have one or more observations`

Can you please confirm once

Ex:
```
t <- ts(c(1,2,3,4,5,6), frequency = 4)

# this will throw error since len(t) <= (m + h)
cal_features(t, seasonal = TRUE, m = 4, lagmax=5L, database = "other", h=2, highfreq = FALSE)

# this works, since len(t) > (m + h)
t <- ts(c(1,2,3,4,5,6,7), frequency = 4)
cal_features(t, seasonal = TRUE, m = 4, lagmax=5L, database = "other", h=2, highfreq = FALSE)

# this will fail, h increased so len(t) <= (m + h)
cal_features(t, seasonal = TRUE, m = 4, lagmax=5L, database = "other", h=3, highfreq = FALSE)

# increase len of t to make it work
t <- ts(c(1,2,3,4,5,6,7,8), frequency = 4)
cal_features(t, seasonal = TRUE, m = 4, lagmax=5L, database = "other", h=3, highfreq = FALSE)
```

this error happens in the function call 
`sEacfy <- stats::acf(sdiff, lag.max = lagmax, plot = FALSE)`
in acf_seasonalDiff, called from line 97 in feature_cal.R

**Comment by thiyangt** [comment]
Let's consider the first example. Similar explanation is applied to others.
`t <- ts(c(1,2,3,4,5,6), frequency = 4)`
`cal_features(t, seasonal = TRUE, m = 4, lagmax=5L, database = "other", h=2, highfreq = FALSE)`

In this case first your time series is split into training period and test period. The training period contains:
```
  Qtr1 Qtr2 Qtr3 Qtr4
1    1    2    3    4
```
and test period contains only last two observations. Features are calculated based on the training period of the time series. In this case you have one observation for each season hence seasonal difference cannot be computed. Hence, the function gives an error message.
